baseurl = "https://www.dxdu.xyz/"
title = "大小多少"

theme = "mainroad"

languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"

paginate = 10
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-166635147-1" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Altaria"
  bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  avatar = "img/avatar.png"

[Params]
  subtitle = "为无为，事无事，味无味。大小多少。" # Subtitle of your site
  description = "John Doe's Personal blog about everything" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
 